import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Slidebar from "@/components/Slidebar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styles from './page.module.css'
import { IndexProvider } from "@/components/IndexProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + styles.body}>
        <IndexProvider>
          <Header />
          <main className={styles.main}>
            <Slidebar />
            <section className={styles.section_main}>
              {children}
            </section>
          </main>
          <Footer />
        </IndexProvider>
      </body>
    </html>
  );
}
