'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MonGrandBloc from "@/components/MonGrandBloc";
import Slidebar from "@/components/Slidebar";
import Header from "@/components/Header";
import ArrowRight from "@/components/ArrowRight";
import ArrowLeft from "@/components/ArrowLeft";
import Footer from "@/components/Footer";
import styles from './page.module.css';
import { ModuleActifProvider } from "@/components/ModuleActifProvider";
import { TitreModuleProvider } from "@/components/TitreModuleProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + styles.body}>
        <ModuleActifProvider>
          <TitreModuleProvider>
            <Header />
            <main className={styles.main}>
              {/* <Slidebar /> */}
              {/* <ArrowRight />
            <ArrowLeft /> */}
              <section className={styles.section_main}>
                <MonGrandBloc />
                <div className={styles.children}>
                  {children}
                </div>
              </section>
            </main>
            <Footer />
          </TitreModuleProvider>
        </ModuleActifProvider>
      </body>
    </html>
  );
}
